### ISSUE TITLE
Storing CA certificates in MokList seems odd

### ISSUE THREAD

**Issue by xnox** [lcp/uefi-fun#1]
I understand that a variable for CA certificates is not specified in the UEFI spec, but it would be nice to use a new variable to store these.

Since as far as I understand the MokList certificates would then be allowed to sign any EFI apps that would become bootable, which might not be desired. (e.g. Let's encrypt CA must not be trusted to sign grubx64.efi).

Also, initrd could extract and trust certificates from the efivars, right? For example, Ubuntu ships openssl in the networked initrds, thus we could add something like `mokutil --export --tls` similar to how there is already `--export --pk|--db|--dbx`.

This would result in stock initrd from distros, being able to fetch custom certs from the efivars without needing to `packcert.sh`.

/me found this repo from following lots of notes things that may have come from @superm1

**Comment by lcp** [comment]
I didn't remember that there is any program in this repo storing CA into MokList, and I won't recommend to do so.
